/**
 * fcBackend-API
 * This is a description of the fcBackend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MonitorStatus from './MonitorStatus';

/**
* The MonitorResponse model module.
* @module model/MonitorResponse
* @version 1.0.0
*/
export default class MonitorResponse {
    /**
    * Constructs a new <code>MonitorResponse</code>.
    * @alias module:model/MonitorResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MonitorResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MonitorResponse} obj Optional instance to populate.
    * @return {module:model/MonitorResponse} The populated <code>MonitorResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorResponse();
                        
            
            if (data.hasOwnProperty('currentTime')) {
                obj['currentTime'] = ApiClient.convertToType(data['currentTime'], 'Date');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('inetAddress')) {
                obj['inetAddress'] = ApiClient.convertToType(data['inetAddress'], 'String');
            }
            if (data.hasOwnProperty('statusSystem')) {
                obj['statusSystem'] = MonitorStatus.constructFromObject(data['statusSystem']);
            }
            if (data.hasOwnProperty('statusRedis')) {
                obj['statusRedis'] = MonitorStatus.constructFromObject(data['statusRedis']);
            }
            if (data.hasOwnProperty('statusOverall')) {
                obj['statusOverall'] = MonitorStatus.constructFromObject(data['statusOverall']);
            }
        }
        return obj;
    }

    /**
    * @member {Date} currentTime
    */
    'currentTime' = undefined;
    /**
    * @member {String} hostname
    */
    'hostname' = undefined;
    /**
    * @member {String} inetAddress
    */
    'inetAddress' = undefined;
    /**
    * @member {module:model/MonitorStatus} statusSystem
    */
    'statusSystem' = undefined;
    /**
    * @member {module:model/MonitorStatus} statusRedis
    */
    'statusRedis' = undefined;
    /**
    * @member {module:model/MonitorStatus} statusOverall
    */
    'statusOverall' = undefined;




}
