/**
 * fcBackend-API
 * This is a description of the fcBackend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MonitorStatus.
* @enum {}
* @readonly
*/
export default class MonitorStatus {
        /**
         * value: "OK"
         * @const
         */
        OK = "OK";

        /**
         * value: "FAILURE"
         * @const
         */
        FAILURE = "FAILURE";

        /**
         * value: "UNKNOWN"
         * @const
         */
        UNKNOWN = "UNKNOWN";


    /**
    * Returns a <code>MonitorStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MonitorStatus} The enum <code>MonitorStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
