/**
 * fcBackend-API
 * This is a description of the fcBackend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SessionId from './SessionId';

/**
* The QuizzSession model module.
* @module model/QuizzSession
* @version 1.0.0
*/
export default class QuizzSession {
    /**
    * Constructs a new <code>QuizzSession</code>.
    * @alias module:model/QuizzSession
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>QuizzSession</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/QuizzSession} obj Optional instance to populate.
    * @return {module:model/QuizzSession} The populated <code>QuizzSession</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuizzSession();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = SessionId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('creationTime')) {
                obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SessionId} id
    */
    'id' = undefined;
    /**
    * @member {Date} creationTime
    */
    'creationTime' = undefined;




}
