/**
 * fcBackend-API
 * This is a description of the fcBackend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SessionId model module.
* @module model/SessionId
* @version 1.0.0
*/
export default class SessionId {
    /**
    * Constructs a new <code>SessionId</code>.
    * an unique string which identifies a session
    * @alias module:model/SessionId
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SessionId</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SessionId} obj Optional instance to populate.
    * @return {module:model/SessionId} The populated <code>SessionId</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionId();
                        
            
        }
        return obj;
    }





}
