/**
 * fcBackend-API
 * This is a description of the fcBackend API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import MonitorResponse from '../model/MonitorResponse';
import QuizzSession from '../model/QuizzSession';
import SessionId from '../model/SessionId';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the monitorGet operation.
     * @callback module:api/DefaultApi~monitorGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns health monitor information
     * A health monitor
     * @param {module:api/DefaultApi~monitorGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorResponse}
     */
    monitorGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MonitorResponse;

      return this.apiClient.callApi(
        '/monitor', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the sessionDelete operation.
     * @callback module:api/DefaultApi~sessionDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * finishs a session
     * @param {module:api/DefaultApi~sessionDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    sessionDelete(sessionId, callback) {
      let postBody = null;

      let pathParams = {
        'sessionId': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/session', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the sessionGet operation.
     * @callback module:api/DefaultApi~sessionGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/QuizzSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a new Quizz Session
     * each Quizz Session has a beginning and an end
     * @param {module:api/DefaultApi~sessionGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/QuizzSession}
     */
    sessionGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = QuizzSession;

      return this.apiClient.callApi(
        '/session', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
